# Generated by Django 6.1 on 2026-08-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='package', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='bracket_data',
            field=models.JSONField(blank=True, help_text='Tournament or Head-to-Head bracket data', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='question_prompt',
            field=models.CharField(blank=True, help_text='Prompt for prediction or trivia games', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='h2h_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='tournament_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('TREASURE_BOX', 'Treasure Box'), ('LOWEST_UNIQUE', 'Lowest Unique Number'), ('HIGHEST_CARD', 'Highest Unique Card'), ('SECRET_NUMBER', 'Secret Number'), ('PREDICTION', 'Prediction Challenge'), ('PRECISION_TIMER', 'Precision Timer'), ('HEAD_TO_HEAD', 'Head-to-Head'), ('TOURNAMENT', 'Tournament')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Electronics', max_length=100),
        ),
    ]
