# Generated by Django 6.1 on 2026-08-21 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_game_bracket_data_game_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='target_time_sec',
            field=models.DecimalField(decimal_places=3, default=Decimal('10.000'), help_text='Custom target time in seconds for Precision Timer challenge', max_digits=6),
        ),
    ]
