# Generated by Django 6.1 on 2026-08-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gameparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='telegram_file_id',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='telegram_message_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_link_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Email and In-App notification preferences'),
        ),
    ]
