# Generated by Django 6.1 on 2026-08-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_paymentsubmission_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Optional Telegram Chat ID for notification mirroring', max_length=100),
        ),
    ]
