# Generated by Django 6.1 on 2026-09-09 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsubmission',
            name='bank',
            field=models.CharField(choices=[('cbe', 'Commercial Bank of Ethiopia'), ('telebirr', 'Telebirr')], default='cbe', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('cbe', 'Commercial Bank of Ethiopia'), ('telebirr', 'Telebirr')], db_index=True, default='cbe', max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('reference_verified', models.BooleanField(default=False)),
                ('amount_verified', models.BooleanField(default=False)),
                ('receiver_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('receipt_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='api.paymentsubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Verification Log',
                'verbose_name_plural': 'Payment Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
