# Generated by Django 5.2.17 on 2026-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_platformsetting_userprofile_ban_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
