# Generated by Django 6.1 on 2026-10-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, default='', help_text='Telegram user first name', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique Telegram User ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text='Telegram @username', max_length=150),
        ),
    ]
